[Host]
gofile.io = 1
fileditch.com = 1
vikingfile.com = 1
buzzheavier.com = 1
litterbox.catbox.moe = 1
filebin.net = 1
1fichier.com = 0
pixeldrain.com = 0

[Settings]
Language = pl

[APIKeys]
;pixeldrain.com = YOUR_API_KEY
